/**:
    ros__parameters:
        map_file_path: "./src/fast_lio/PCD/"
        common:
            lid_topic:  "/livox/lidar"
            imu_topic:  "/livox/imu"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
            # 重定位
            reloc_en: false       # true: use priori global map

        preprocess:
            lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
            scan_line:  4
            blind: 0.1
            timestamp_unit: 3
            scan_rate: 10
            body_filter: true # 是否滤除车体
            body_radius: 0.33
            body_height: 0.7

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    360.0
            det_range:     450.0
            extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
            extrinsic_T: [ -0.011, -0.0234, 0.044 ]
            extrinsic_R: [ 1., 0., 0.,
                            0., 1., 0.,
                            0., 0., 1.]

        initialPose:
            use: true  #blue=true,red=false
            position:
                x: 0.000 #0.07
                y: 0.000 #-0.235
                z: 0.000 #0.45
            orientation:
                w: 1.000 #0.656
                x: 0.000 #0.265
                y: 0.000 #0.276
                z: 0.000 #-0.651

        lidar_extrinsic: #body2lidar
            position:
                x: 0.0575
                y: 0.0
                z: 0.55
            orientation:
                w: 0.0
                x: -0.707
                y: 0.707
                z: 0.000            
        
        publish:
            path_en: true                # true: publish Path
            effect_map_en: false         # true: publish Effects
            map_en: true                # true: publish Map cloud
            scan_publish_en: true       # false: close all the point cloud output
            dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

        pcd_save:
            pcd_save_en: false
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
